# Site settings
title: 狡诈小丑
email: jiaozhaxiaochou@163.com
description: > # HI,I'm ...大家好我初次使用github pages。网站正在建设中
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codenerull.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  CodeNerull
ASSET_PATH : "/assets"
sass:
  sass_dir: "/assets/_sass"

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"